parameters:
    author_manager.class: Blog\CoreBundle\Services\AuthorManager
    post_manager.class: Blog\CoreBundle\Services\PostManager
    tag_manager.class: Blog\CoreBundle\Services\TagManager
    string_decorator.class: Blog\CoreBundle\Twig\AppExtension

services:
    author_manager:
        class: %author_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
    post_manager:
        class: %post_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@form.factory"
    tag_manager:
            class: %tag_manager.class%
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@form.factory"
    twig.string_decorator:
            class: %string_decorator.class%
            arguments:
                - %decorator.char%
            tags:
                - { name: twig.extension }